{% set name = "px-proxy" %}
{% set version = "2019-05-20" %}

package:
  name: {{ name|lower }}
  version: {{ version|replace("-", ".") }}

source:
  url: https://github.com/genotrance/{{ name[:2] }}/archive/{{ version }}.tar.gz
  sha256: 158c1c517a214cacbbb8421c03b54507595f796559ffd5482e9f632e2c6fbfa3

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [not win]
  entry_points:
    - px = px:main

requirements:
  host:
    - python
    - pip
  run:
    - python
    - futures  # [py2k]
    - keyring
    - netaddr
    - ntlm-auth
    - psutil
    - pywin32
    - winkerberos

test:
  imports:
    - px

about:
  home: https://github.com/genotrance/px
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: An HTTP proxy server to automatically authenticate through an NTLM proxy
  description: |
    Px is a HTTP(s) proxy server that allows applications to authenticate through
    an NTLM or Windows Kerberos authenticated proxy server, typically used in
    corporate deployments, without having to deal with the actual handshake. It is
    primarily designed to run on Windows systems and authenticates on behalf of the
    application using the currently logged in Windows user account.

extra:
  recipe-maintainers:
    - fcollonval
    - genotrance
