{% set name = "px-proxy" %}
{% set version = "0.9.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/genotrance/{{ name[:2] }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: f896412a560a10b4cc95776cb43d853641920fff4ba1886c83844fcffd0f63d9
  patches:
    - libcurl-win-dll-path.patch

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - px = px.main:main

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - keyring
    - libcurl
    - netaddr
    - psutil
    - pyspnego
    - python
    - python-dotenv
    - python-quickjs

test:
  imports:
    - px
  commands:
    - px -h

about:
  home: https://github.com/genotrance/px
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: 'An HTTP proxy server to automatically authenticate through an NTLM proxy'
  description: |
    Px is a HTTP(s) proxy server that allows applications to authenticate through
    an NTLM or Windows Kerberos authenticated proxy server, typically used in
    corporate deployments, without having to deal with the actual handshake. It is
    primarily designed to run on Windows systems and authenticates on behalf of the
    application using the currently logged in Windows user account.

extra:
  recipe-maintainers:
    - fcollonval
    - genotrance
    - m-rossi
