travis:
  secure:
    BINSTAR_TOKEN: YukeOnyvfHc7L3tAU4Ccyr7PzY9jOtIzhh/yCmCKQShzTQyRnDdhVYCZb6D57YcznH/eOC2smKULmdruFq8ObDVj5uXErQyBycef6xIjxeR8jH/+b5filw7VOf49XBQQUwVDMLwzcEY4kdMvPZsWGwcDLZLASxevjfR5e9JzxlYb+NNhaX42knJ2x71aSx/f7sT1y/gvGuMVsRz7VM1DQZo6hLhyGyxNzIMkhAxQFuIIIX4UVapcJ+SQLBLNewvSm33m9d2FrN/ka6dnMx2LIDRS9mGHp4U/4L27donLWAJlay72a6VptY8PYD4J8buX3/AlpGqkFhQT8LkqAshROHjH1SWd6y/uB0Q4dPVoiSwLwpSQgb2BJizIp7b2391pF9ApPgbVxaJOBqMGYFmoZyJWNXpYKdtBv9g7Sa41nBJq66ClGkJ/YgQQogIQuseQT9x7roCRM7F9xwBferrwNSMeBG0BYFXLrzL/yRk1OYReJqRs02HVSOLloiNyqiPbwDZp+NeK/DZLvwA4u18DM6LJ93tgmox0xlfU0YL/vtE/J/mACUZwYR5QYZRwIIsnIZKV3vfV+n1wGivD+3nysMVeyxJcNZ1wWXefAQQp0neanNbzSRe2UmOzKhlZfNAx7XNszC3HU5S/LeHDwA31z2FSrKIzFbH2ymXleix/xe8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
